templates.score_dialog = 
   ['<div class="reveal" id="score_dialog_modal"><% console.log(data); %>',
    '   <h1>Ergebnis</h1>',
    '   <div>Ihr Ergebnis: <strong><%= data.score %></strong> von 100 Punkten!</div>',
    '   <div>',
    '   <% if (data.score <= 50) { %>',
    '       Das geht aber besser!',
    '   <% } else if (data.score <= 80) { %>',
    '       Nicht schlecht!',
    '   <% } else { %>',
    '       Beeindruckend!',
    '   <% } %>',
    '   </div>',
    '   <div><small>Sie können ein neues Spiel starten oder diesen Dialog wegklicken und weiter an Ihrem Pfad arbeiten!</small></div>',
    '   <div><button id="start_new_round_button" class="button">Neues Spiel</button></div>',
    '   <button class="close-button" data-close aria-label="Close modal" type="button">',
    '        <span aria-hidden="true">&times;</span>',
    '   </button>',
    '</div>'].join('\n');
