templates.title_bar = 
   ['<div class="row title-bar">',
    '   <div class="small-12 medium-12 large-5 columns" id="game_name">',
    '       <h1>Navigationsspiel</h1>',
    '   </div>',
    '   <div class="small-3 medium-2 columns" id="save_wrapper">',
    '       <div class="save_game">',
    '           <button class="button" id="save_button"><i class="fi-save"></i> Save</button>',
    '       </div>',
    '   </div>',
    '   <div class="small-6 medium-6 large-3 columns" id="session_id_wrapper">',
    '       <div id="session_id_container">&nbsp;',
    '       </div>',
    '   </div>',
    '   <div class="small-3 medium-2 columns" id="new_game_wrapper">',
    '       <div class="load_game">',
    '           <button class="button" id="new_game_button"><i class="fi-page-add"></i> New Game</button>',
    '       </div>',
    '   </div>',
    '</div>',
    '<div class="row">',
    '   <div class="small-6 columns">',
    '       <span id="from_node">Start</span>',
    '   </div>',
    '   <div class="small-6 columns">',
    '       <span id="to_node">Ziel</span>',
    '   </div>',
    '</div>'].join('\n');
